general.import = [
    "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
]


general.live_config_reload = true
[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.7

[font]
size = 15.0

[font.bold]
family = "Firacode"
style = "Heavy"

[font.bold_italic]
family = "Firacode"
style = "Heavy Italic"

[font.italic]
family = "Firacode"
style = "Medium Italic"

[font.normal]
family = "Firacode"
style = "Medium"
